version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
    networks:
      - clarusnet
  bookstore-app: 
    image: toptasc/webserver13:latest
    container_name: bookstore
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - clarusnet
networks:
  clarusnet:
    driver: bridge